version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: DiscordBot

    ports:
      - 27017:27017
    volumes:
      - ./mongo-db:/data/db
      - ./mongo-db/config:/data/config
      - ./mongo-db/logs:/data/logs
    env_file:
      - ./.env

  mongo_express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    depends_on:
      - mongo_db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_PORT: 27017

    volumes:
      - ./overwrite/router.js:/node_modules/mongo-express/lib/router.js
    env_file:
      - ./.env

  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord_bot
    restart: always
    env_file:
      - ./.env
